sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t AbhishekKaushik16/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true AbhishekKaushik16/docker-react npm run test
